### PR TITLE
Switches primary language, Malagasy into English

### PR DESCRIPTION
**Pull request by lightme-fan**
Hello there,

In this branch, we changed the primary language which was Malagasy. So, we switched it into English.
This is the [branch link](https://github.com/onja-org/malagasy-rn-Bismuth/tree/fix-bug).

Thank you!

### CODE REVIEW

**Comment by constantingoeldel** [comment]
Fix bug is not a descriptive branch name, quite the opposite

**Review by constantingoeldel — APPROVED** [review]
Looks good to me

**Comment by constantingoeldel** [comment]
Choose a better branch name next time

**Comment by ravinalamada** [comment]
It looks great

**Review by ravinalamada — APPROVED** [review]

**Review by Tiaraha-funny — APPROVED** [review]

**Pull request merged**
